### ISSUE TITLE
How to test plugins that depend on other plugins

### ISSUE THREAD

**Issue by mhedgpeth** [burtlo/chefspec-ohai#2]
I'm trying to test this plugin:

```ruby
Ohai.plugin :company do
  provides 'company/datacenter'
  depends 'hostname'

  collect_data :default do
    company(Mash.new)
    host = hostname[:hostname]
    match = /(\D\D\D\d\d)-.*/.match(host)
      if !match.nil?
       company[:datacenter] = match[0]
     else
      company[:datacenter] = 'CORP'
     end
  end
end
```

With this test:

```ruby
require 'spec_helper'

describe_ohai_plugin :Ncr do
  let(:plugin_file) { 'files/default/ncr_datacenter.rb' }

  it 'provides ncr/datacenter' do
    expect(plugin).to provides_attribute('ncr/datacenter')
  end

  let(:command) { double('Fake Command', stdout: 'OUTPUT') }

  it 'correctly parses machine name from ATL32' do
    allow(plugin).to receive(:shell_out).with('hostname').and_return('ATL32-mysql01')
    expect(plugin_attribute('company/datacenter')).to eq('ATL32')
  end

  it 'parses machine name with no prefix to be CORP' do
    allow(plugin).to receive(:shell_out).with('hostname').and_return('labweb01')
    expect(plugin_attribute('company/datacenter')).to eq('CORP')
  end
end
```

And when I run it I get the following error:

```
  1) company correctly parses machine name from ATL32
     Failure/Error: expect(plugin_attribute('company/datacenter')).to eq('ATL32')

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # files/default:7:in `block (2 levels) in <main>'
     # /Users/mh185122/.chefdk/gem/ruby/2.3.0/gems/chefspec-ohai-0.1.0/lib/chefspec/ohai.rb:92:in `plugin_attribute'
     # ./spec/unit/ohai_plugins/company_datacenter_spec.rb:14:in `block (2 levels) in <top (required)>'
```

It works fine until I add the hostname dependency. How would I refer to the active hostname built into ohai?

**Comment by mhedgpeth** [comment]
This issue can be closed. This was actually a bug in my plugin, not in the gem
